---
kind: Namespace
apiVersion: v1
metadata:
  name: &name argo
  annotations:
    argocd.argoproj.io/sync-options: >-
      ServerSideApply=true,
      Prune=false,
      Replace=false,
      Force=false
  labels:
    app.kubernetes.io/name: *name
    name: *name
